### ISSUE TITLE
Make gh-pages default branch

### ISSUE THREAD

**Issue by danswick** [maptime/chicago#1]
@geografa or @almccon , I'm hoping to set up a Chicago chapter page a-la maptime.github.io/toronto and have done some (possibly misguided) setup. I've forked the `starter` repo, changed the `_config.yml` file, and everything seems to be working over at [maptime.github.io/chicago](http://maptime.github.io/chicago). 

Still need to start changing the default content, but wanted to ping you guys to make sure this is the proper protocol. Aside from dropping in meaningful content, is there anything else I should be aware of? 

Also, is it possible to make gh-pages the default branch? Or does that matter? 

Thanks!

**Comment by geografa** [comment]
Looks good @danswick !

> Also, is it possible to make gh-pages the default branch? Or does that matter?

No - you'll want that. The main site is the only repo that needs to be `master`. I _did_ get a jekyll build error on the CNAME but that may be related to the domain being `maptime.github.io` rather than the `maptime.io` site. We'll cross that bridge when we test this as a live site.

**Comment by danswick** [comment]
Sorry for being dense, @geografa, but does that mean the `master` branch of this repo needs to be removed? I don't think I have permission to set the default branch.

**Comment by geografa** [comment]
No - sorry, I don't think I was clear. The master branch can be removed if
it causes confusion but leaving it for now is fine. Setting the gh-pages
branch to default is a good idea.

On Monday, September 22, 2014, Dan Swick notifications@github.com wrote:

> Sorry for being dense, but does that mean the master branch of this repo
> needs to be removed? I don't think I have permission to set the default
> branch.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/maptime/chicago/issues/1#issuecomment-56471578.

## 

Rafa Gutierrez
help@mapbox.com

**Comment by danswick** [comment]
Thanks for the clarification, @geografa. Do you have the proper permissions to set `gh-pages` as the default? I can't make changes to the settings of this repo.

**Comment by geografa** [comment]
All good here. Sorry, we took away repo control except for just a few folks and looks like just changing the default branch requires admin privs. Let me know if you need anything else.

**Comment by danswick** [comment]
:thumbsup: Thanks!

**Comment by bethschechter** [comment]
@geografa you are on fire this morning! thank you!

## 

Beth Schechter
Education + Outreach, Stamen Design http://stamen.com/
Founder, Maptime http://maptime.io/
+1 415-558-1610
